package com.example.newform.database;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import com.example.newform.models.AlunoModel;
import com.example.newform.models.CidadeModel;
import com.example.newform.models.FaturaMatriculaModel;
import com.example.newform.models.GraduacaoModel;
import com.example.newform.models.MatriculaModalidadeModel;
import com.example.newform.models.MatriculaModel;
import com.example.newform.models.ModalidadeModel;
import com.example.newform.models.PlanoModel;

public class DBOpenHelper extends SQLiteOpenHelper {

    private static final String DATABASE_NOME = "newform.db";
    private static final int DATABASE_VERSAO = 5;

    /**
     * Construtor padrão da classe.
     * @param context
     *          Activity responsável por montar o banco.
     */
    public DBOpenHelper(Context context) {
        super(context, DATABASE_NOME, null, DATABASE_VERSAO);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL(CidadeModel.CREATE_TABLE);
        db.execSQL(AlunoModel.CREATE_TABLE);
        db.execSQL(MatriculaModel.CREATE_TABLE);
        db.execSQL(ModalidadeModel.CREATE_TABLE);
        db.execSQL(PlanoModel.CREATE_TABLE);
        db.execSQL(GraduacaoModel.CREATE_TABLE);
        db.execSQL(FaturaMatriculaModel.CREATE_TABLE);
        db.execSQL(MatriculaModalidadeModel.CREATE_TABLE);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        switch (newVersion) {
            case 5:
                inserirCidades(db);
                break;
        }
    }

    private void inserirCidades(SQLiteDatabase db){
        String[] cidades = {
        "insert into tb_cidades values('SAO BONIFACIO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO CARLOS','SC', 'Brasil')",
        "insert into tb_cidades values('SAO CRISTOVAO','SC', 'Brasil')",
        "insert into tb_cidades values('DIONISIO CERQUEIRA','SC', 'Brasil')",
        "insert into tb_cidades values('DESCANSO','SC', 'Brasil')",
        "insert into tb_cidades values('DALBERGIA','SC', 'Brasil')",
        "insert into tb_cidades values('DAL PAI','SC', 'Brasil')",
        "insert into tb_cidades values('CURITIBANOS','SC', 'Brasil')",
        "insert into tb_cidades values('CUNHATAI','SC', 'Brasil')",
        "insert into tb_cidades values('CUNHA PORA','SC', 'Brasil')",
        "insert into tb_cidades values('CRICIUMA','SC', 'Brasil')",
        "insert into tb_cidades values('CORUPA','SC', 'Brasil')",
        "insert into tb_cidades values('CORREIA PINTO','SC', 'Brasil')",
        "insert into tb_cidades values('CORONEL MARTINS','SC', 'Brasil')",
        "insert into tb_cidades values('CORONEL FREITAS','SC', 'Brasil')",
        "insert into tb_cidades values('CORDILHEIRA ALTA','SC', 'Brasil')",
        "insert into tb_cidades values('CONCORDIA','SC', 'Brasil')",
        "insert into tb_cidades values('COLONIA SANTANA','SC', 'Brasil')",
        "insert into tb_cidades values('COLONIA SANTA TEREZA','SC', 'Brasil')",
        "insert into tb_cidades values('COCAL DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('CLARAIBA','SC', 'Brasil')",
        "insert into tb_cidades values('CHAPECO','SC', 'Brasil')",
        "insert into tb_cidades values('CHAPADAO DO LAGEADO','SC', 'Brasil')",
        "insert into tb_cidades values('CERRO NEGRO','SC', 'Brasil')",
        "insert into tb_cidades values('CELSO RAMOS','SC', 'Brasil')",
        "insert into tb_cidades values('CEDRO ALTO','SC', 'Brasil')",
        "insert into tb_cidades values('CAXAMBU DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('CATUIRA','SC', 'Brasil')",
        "insert into tb_cidades values('CATANDUVAS','SC', 'Brasil')",
        "insert into tb_cidades values('CARAIBA','SC', 'Brasil')",
        "insert into tb_cidades values('CAPIVARI DE BAIXO','SC', 'Brasil')",
        "insert into tb_cidades values('CAPINZAL','SC', 'Brasil')",
        "insert into tb_cidades values('CAPAO ALTO','SC', 'Brasil')",
        "insert into tb_cidades values('CANOINHAS','SC', 'Brasil')",
        "insert into tb_cidades values('CANOAS','SC', 'Brasil')",
        "insert into tb_cidades values('CANELINHA','SC', 'Brasil')",
        "insert into tb_cidades values('CANASVIEIRAS','SC', 'Brasil')",
        "insert into tb_cidades values('CAMPOS NOVOS','SC', 'Brasil')",
        "insert into tb_cidades values('CAMPO ERE','SC', 'Brasil')",
        "insert into tb_cidades values('CAMPO BELO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('CAMPO ALEGRE','SC', 'Brasil')",
        "insert into tb_cidades values('CAMPINAS','SC', 'Brasil')",
        "insert into tb_cidades values('CAMPECHE','SC', 'Brasil')",
        "insert into tb_cidades values('CAMBUINZAL','SC', 'Brasil')",
        "insert into tb_cidades values('CAMBORIU','SC', 'Brasil')",
        "insert into tb_cidades values('CALMON','SC', 'Brasil')",
        "insert into tb_cidades values('CAIBI','SC', 'Brasil')",
        "insert into tb_cidades values('CACHOEIRA DO BOM JESUS','SC', 'Brasil')",
        "insert into tb_cidades values('CACHOEIRA DE FATIMA','SC', 'Brasil')",
        "insert into tb_cidades values('CACADOR','SC', 'Brasil')",
        "insert into tb_cidades values('BRUSQUE','SC', 'Brasil')",
        "insert into tb_cidades values('BRUNOPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('BRACO DO TROMBUDO','SC', 'Brasil')",
        "insert into tb_cidades values('BRACO DO NORTE','SC', 'Brasil')",
        "insert into tb_cidades values('BOTUVERA','SC', 'Brasil')",
        "insert into tb_cidades values('BOMBINHAS','SC', 'Brasil')",
        "insert into tb_cidades values('BOM SUCESSO','SC', 'Brasil')",
        "insert into tb_cidades values('BOM RETIRO','SC', 'Brasil')",
        "insert into tb_cidades values('BOM JESUS DO OESTE','SC', 'Brasil')",
        "insert into tb_cidades values('BOM JESUS','SC', 'Brasil')",
        "insert into tb_cidades values('SAO CRISTOVAO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('SAO DEFENDE','SC', 'Brasil')",
        "insert into tb_cidades values('SAO DOMINGOS','SC', 'Brasil')",
        "insert into tb_cidades values('SAO FRANCISCO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('SAO GABRIEL','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOAO BATISTA','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOAO DO ITAPERIU','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOAO DO OESTE','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOAO DO RIO VERMELHO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOAO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOAQUIM','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOSE','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOSE DO CEDRO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOSE DO CERRITO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO JOSE DO LARANJAL','SC', 'Brasil')",
        "insert into tb_cidades values('SAO LEONARDO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO LOURENCO DO OESTE','SC', 'Brasil')",
        "insert into tb_cidades values('SAO LUDGERO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO MARTINHO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO MIGUEL D''OESTE','SC', 'Brasil')",
        "insert into tb_cidades values('SAO MIGUEL DA BOA VISTA','SC', 'Brasil')",
        "insert into tb_cidades values('SAO MIGUEL DA SERRA','SC', 'Brasil')",
        "insert into tb_cidades values('SAO PEDRO DE ALCANTARA','SC', 'Brasil')",
        "insert into tb_cidades values('SAO PEDRO TOBIAS','SC', 'Brasil')",
        "insert into tb_cidades values('SAO ROQUE','SC', 'Brasil')",
        "insert into tb_cidades values('SAO SEBASTIAO DO ARVOREDO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO SEBASTIAO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('SAPIRANGA','SC', 'Brasil')",
        "insert into tb_cidades values('SAUDADES','SC', 'Brasil')",
        "insert into tb_cidades values('SCHROEDER','SC', 'Brasil')",
        "insert into tb_cidades values('SEARA','SC', 'Brasil')",
        "insert into tb_cidades values('SEDE OLDEMBURG','SC', 'Brasil')",
        "insert into tb_cidades values('SERRA ALTA','SC', 'Brasil')",
        "insert into tb_cidades values('SERTAO DO MARUIM','SC', 'Brasil')",
        "insert into tb_cidades values('SIDEROPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('SOMBRIO','SC', 'Brasil')",
        "insert into tb_cidades values('SOROCABA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('SUL BRASIL','SC', 'Brasil')",
        "insert into tb_cidades values('TAIO','SC', 'Brasil')",
        "insert into tb_cidades values('TANGARA','SC', 'Brasil')",
        "insert into tb_cidades values('TAQUARA VERDE','SC', 'Brasil')",
        "insert into tb_cidades values('TAQUARAS','SC', 'Brasil')",
        "insert into tb_cidades values('TIGIPIO','SC', 'Brasil')",
        "insert into tb_cidades values('TIGRINHOS','SC', 'Brasil')",
        "insert into tb_cidades values('TIJUCAS','SC', 'Brasil')",
        "insert into tb_cidades values('TIMBE DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('TIMBO','SC', 'Brasil')",
        "insert into tb_cidades values('TIMBO GRANDE','SC', 'Brasil')",
        "insert into tb_cidades values('TRES BARRAS','SC', 'Brasil')",
        "insert into tb_cidades values('TREVISO','SC', 'Brasil')",
        "insert into tb_cidades values('TREZE DE MAIO','SC', 'Brasil')",
        "insert into tb_cidades values('TREZE TILIAS','SC', 'Brasil')",
        "insert into tb_cidades values('TROMBUDO CENTRAL','SC', 'Brasil')",
        "insert into tb_cidades values('TUBARAO','SC', 'Brasil')",
        "insert into tb_cidades values('TUNAPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('TUPITINGA','SC', 'Brasil')",
        "insert into tb_cidades values('TURVO','SC', 'Brasil')",
        "insert into tb_cidades values('UNIAO DO OESTE','SC', 'Brasil')",
        "insert into tb_cidades values('URUBICI','SC', 'Brasil')",
        "insert into tb_cidades values('URUGUAI','SC', 'Brasil')",
        "insert into tb_cidades values('URUPEMA','SC', 'Brasil')",
        "insert into tb_cidades values('URUSSANGA','SC', 'Brasil')",
        "insert into tb_cidades values('VARGEAO','SC', 'Brasil')",
        "insert into tb_cidades values('VARGEM','SC', 'Brasil')",
        "insert into tb_cidades values('VARGEM BONITA','SC', 'Brasil')",
        "insert into tb_cidades values('VARGEM DO CEDRO','SC', 'Brasil')",
        "insert into tb_cidades values('VIDAL RAMOS','SC', 'Brasil')",
        "insert into tb_cidades values('VIDEIRA','SC', 'Brasil')",
        "insert into tb_cidades values('VILA CONCEICAO','SC', 'Brasil')",
        "insert into tb_cidades values('VILA DE VOLTA GRANDE','SC', 'Brasil')",
        "insert into tb_cidades values('VILA MILANI','SC', 'Brasil')",
        "insert into tb_cidades values('VILA NOVA','SC', 'Brasil')",
        "insert into tb_cidades values('VITOR MEIRELES','SC', 'Brasil')",
        "insert into tb_cidades values('WITMARSUM','SC', 'Brasil')",
        "insert into tb_cidades values('XANXERE','SC', 'Brasil')",
        "insert into tb_cidades values('XAVANTINA','SC', 'Brasil')",
        "insert into tb_cidades values('XAXIM','SC', 'Brasil')",
        "insert into tb_cidades values('ZORTEA','SC', 'Brasil')",
        "insert into tb_cidades values('PRINCESA','SC', 'Brasil')",
        "insert into tb_cidades values('QUARTA LINHA','SC', 'Brasil')",
        "insert into tb_cidades values('QUILOMBO','SC', 'Brasil')",
        "insert into tb_cidades values('QUILOMETRO DOZE','SC', 'Brasil')",
        "insert into tb_cidades values('RANCHO QUEIMADO','SC', 'Brasil')",
        "insert into tb_cidades values('RATONES','SC', 'Brasil')",
        "insert into tb_cidades values('RESIDENCIA FUCK','SC', 'Brasil')",
        "insert into tb_cidades values('RIBEIRAO DA ILHA','SC', 'Brasil')",
        "insert into tb_cidades values('RIBEIRAO PEQUENO','SC', 'Brasil')",
        "insert into tb_cidades values('RIO ANTINHA','SC', 'Brasil')",
        "insert into tb_cidades values('RIO BONITO','SC', 'Brasil')",
        "insert into tb_cidades values('RIO D''UNA','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DA ANTA','SC', 'Brasil')",
        "insert into tb_cidades values('MAJOR GERCINO','SC', 'Brasil')",
        "insert into tb_cidades values('MAFRA','SC', 'Brasil')",
        "insert into tb_cidades values('MACIEIRA','SC', 'Brasil')",
        "insert into tb_cidades values('MACHADOS','SC', 'Brasil')",
        "insert into tb_cidades values('LUZERNA','SC', 'Brasil')",
        "insert into tb_cidades values('LUIZ ALVES','SC', 'Brasil')",
        "insert into tb_cidades values('LOURDES','SC', 'Brasil')",
        "insert into tb_cidades values('LONTRAS','SC', 'Brasil')",
        "insert into tb_cidades values('LINHA DAS PALMEIRAS','SC', 'Brasil')",
        "insert into tb_cidades values('LINDOIA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('LEOBERTO LEAL','SC', 'Brasil')",
        "insert into tb_cidades values('LEBON REGIS','SC', 'Brasil')",
        "insert into tb_cidades values('LEAO','SC', 'Brasil')",
        "insert into tb_cidades values('LAURO MULLER','SC', 'Brasil')",
        "insert into tb_cidades values('LAURENTINO','SC', 'Brasil')",
        "insert into tb_cidades values('LAJEADO GRANDE','SC', 'Brasil')",
        "insert into tb_cidades values('LAGUNA','SC', 'Brasil')",
        "insert into tb_cidades values('LAGOA DA ESTIVA','SC', 'Brasil')",
        "insert into tb_cidades values('LAGOA','SC', 'Brasil')",
        "insert into tb_cidades values('LAGES','SC', 'Brasil')",
        "insert into tb_cidades values('LACERDOPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('JUPIA','SC', 'Brasil')",
        "insert into tb_cidades values('JOSE BOITEUX','SC', 'Brasil')",
        "insert into tb_cidades values('JOINVILLE','SC', 'Brasil')",
        "insert into tb_cidades values('JOACABA','SC', 'Brasil')",
        "insert into tb_cidades values('JARDINOPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('JARAGUA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('JAGUARUNA','SC', 'Brasil')",
        "insert into tb_cidades values('JACINTO MACHADO','SC', 'Brasil')",
        "insert into tb_cidades values('JABORA','SC', 'Brasil')",
        "insert into tb_cidades values('ITUPORANGA','SC', 'Brasil')",
        "insert into tb_cidades values('ITOUPAVA','SC', 'Brasil')",
        "insert into tb_cidades values('ITAPOCU','SC', 'Brasil')",
        "insert into tb_cidades values('ITAPOA','SC', 'Brasil')",
        "insert into tb_cidades values('ITAPIRANGA','SC', 'Brasil')",
        "insert into tb_cidades values('ITAPEMA','SC', 'Brasil')",
        "insert into tb_cidades values('ITAJUBA','SC', 'Brasil')",
        "insert into tb_cidades values('ITAJAI','SC', 'Brasil')",
        "insert into tb_cidades values('ITAIOPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('ITAIO','SC', 'Brasil')",
        "insert into tb_cidades values('ITA','SC', 'Brasil')",
        "insert into tb_cidades values('IRINEOPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('IRATI','SC', 'Brasil')",
        "insert into tb_cidades values('IRAPUTA','SC', 'Brasil')",
        "insert into tb_cidades values('IRANI','SC', 'Brasil')",
        "insert into tb_cidades values('IRAKITAN','SC', 'Brasil')",
        "insert into tb_cidades values('IRACEMINHA','SC', 'Brasil')",
        "insert into tb_cidades values('IPUMIRIM','SC', 'Brasil')",
        "insert into tb_cidades values('IPUACU','SC', 'Brasil')",
        "insert into tb_cidades values('IPORA DO OESTE','SC', 'Brasil')",
        "insert into tb_cidades values('IPOMEIA','SC', 'Brasil')",
        "insert into tb_cidades values('IPIRA','SC', 'Brasil')",
        "insert into tb_cidades values('IOMERE','SC', 'Brasil')",
        "insert into tb_cidades values('INVERNADA','SC', 'Brasil')",
        "insert into tb_cidades values('INGLESES DO RIO VERMELHO','SC', 'Brasil')",
        "insert into tb_cidades values('INDIOS','SC', 'Brasil')",
        "insert into tb_cidades values('INDAIAL','SC', 'Brasil')",
        "insert into tb_cidades values('IMBUIA','SC', 'Brasil')",
        "insert into tb_cidades values('IMBITUBA','SC', 'Brasil')",
        "insert into tb_cidades values('IMARUI','SC', 'Brasil')",
        "insert into tb_cidades values('ILHOTA','SC', 'Brasil')",
        "insert into tb_cidades values('ICARA','SC', 'Brasil')",
        "insert into tb_cidades values('IBIRAMA','SC', 'Brasil')",
        "insert into tb_cidades values('IBICUI','SC', 'Brasil')",
        "insert into tb_cidades values('IBICARE','SC', 'Brasil')",
        "insert into tb_cidades values('IBIAM','SC', 'Brasil')",
        "insert into tb_cidades values('HERVAL D''OESTE','SC', 'Brasil')",
        "insert into tb_cidades values('HERCILIOPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('HERCILIO LUZ','SC', 'Brasil')",
        "insert into tb_cidades values('GUATAMBU','SC', 'Brasil')",
        "insert into tb_cidades values('GUATA','SC', 'Brasil')",
        "insert into tb_cidades values('GUARUJA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('GUARAMIRIM','SC', 'Brasil')",
        "insert into tb_cidades values('GUARACIABA','SC', 'Brasil')",
        "insert into tb_cidades values('GUAPORANGA','SC', 'Brasil')",
        "insert into tb_cidades values('GUABIRUBA','SC', 'Brasil')",
        "insert into tb_cidades values('GRAVATAL','SC', 'Brasil')",
        "insert into tb_cidades values('GRAPIA','SC', 'Brasil')",
        "insert into tb_cidades values('GRAO PARA','SC', 'Brasil')",
        "insert into tb_cidades values('GOVERNADOR CELSO RAMOS','SC', 'Brasil')",
        "insert into tb_cidades values('GOIO-EN','SC', 'Brasil')",
        "insert into tb_cidades values('GASPAR','SC', 'Brasil')",
        "insert into tb_cidades values('GARUVA','SC', 'Brasil')",
        "insert into tb_cidades values('GAROPABA','SC', 'Brasil')",
        "insert into tb_cidades values('GARCIA','SC', 'Brasil')",
        "insert into tb_cidades values('GALVAO','SC', 'Brasil')",
        "insert into tb_cidades values('FREI ROGERIO','SC', 'Brasil')",
        "insert into tb_cidades values('FREDERICO WASTNER','SC', 'Brasil')",
        "insert into tb_cidades values('FRAIBURGO','SC', 'Brasil')",
        "insert into tb_cidades values('FRAGOSOS','SC', 'Brasil')",
        "insert into tb_cidades values('FORQUILHINHA','SC', 'Brasil')",
        "insert into tb_cidades values('FORMOSA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('FLORIANOPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('FLOR DO SERTAO','SC', 'Brasil')",
        "insert into tb_cidades values('FIGUEIRA','SC', 'Brasil')",
        "insert into tb_cidades values('FELIPE SCHMIDT','SC', 'Brasil')",
        "insert into tb_cidades values('FAZENDA ZANDAVALLI','SC', 'Brasil')",
        "insert into tb_cidades values('FAXINAL DOS GUEDES','SC', 'Brasil')",
        "insert into tb_cidades values('ESTACAO COCAL','SC', 'Brasil')",
        "insert into tb_cidades values('ESPINILHO','SC', 'Brasil')",
        "insert into tb_cidades values('ERVAL VELHO','SC', 'Brasil')",
        "insert into tb_cidades values('ERMO','SC', 'Brasil')",
        "insert into tb_cidades values('ENTRE RIOS','SC', 'Brasil')",
        "insert into tb_cidades values('ENSEADA DE BRITO','SC', 'Brasil')",
        "insert into tb_cidades values('ENGENHO VELHO','SC', 'Brasil')",
        "insert into tb_cidades values('DOUTOR PEDRINHO','SC', 'Brasil')",
        "insert into tb_cidades values('DONA EMMA','SC', 'Brasil')",
        "insert into tb_cidades values('PRESIDENTE NEREU','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DA LUZ','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DAS ANTAS','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DAS FURNAS','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DO CAMPO','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DO OESTE','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DOS BUGRES','SC', 'Brasil')",
        "insert into tb_cidades values('RIO DOS CEDROS','SC', 'Brasil')",
        "insert into tb_cidades values('RIO FORTUNA','SC', 'Brasil')",
        "insert into tb_cidades values('RIO MAINA','SC', 'Brasil')",
        "insert into tb_cidades values('RIO NEGRINHO','SC', 'Brasil')",
        "insert into tb_cidades values('RIO PRETO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('RIO RUFINO','SC', 'Brasil')",
        "insert into tb_cidades values('RIQUEZA','SC', 'Brasil')",
        "insert into tb_cidades values('RODEIO','SC', 'Brasil')",
        "insert into tb_cidades values('ROMELANDIA','SC', 'Brasil')",
        "insert into tb_cidades values('SAI','SC', 'Brasil')",
        "insert into tb_cidades values('SALETE','SC', 'Brasil')",
        "insert into tb_cidades values('SALTINHO','SC', 'Brasil')",
        "insert into tb_cidades values('SALTO VELOSO','SC', 'Brasil')",
        "insert into tb_cidades values('SANGA DA TOCA','SC', 'Brasil')",
        "insert into tb_cidades values('SANGAO','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA CECILIA','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA CRUZ DO TIMBO','SC', 'Brasil')",
        "insert into tb_cidades values('BOM JARDIM DA SERRA','SC', 'Brasil')",
        "insert into tb_cidades values('BOITEUXBURGO','SC', 'Brasil')",
        "insert into tb_cidades values('BOCAINA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('BLUMENAU','SC', 'Brasil')",
        "insert into tb_cidades values('BIGUACU','SC', 'Brasil')",
        "insert into tb_cidades values('BENEDITO NOVO','SC', 'Brasil')",
        "insert into tb_cidades values('BELMONTE','SC', 'Brasil')",
        "insert into tb_cidades values('BELA VISTA DO TOLDO','SC', 'Brasil')",
        "insert into tb_cidades values('BELA VISTA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('BELA VISTA','SC', 'Brasil')",
        "insert into tb_cidades values('BATEIAS DE BAIXO','SC', 'Brasil')",
        "insert into tb_cidades values('BARRO BRANCO','SC', 'Brasil')",
        "insert into tb_cidades values('BARREIROS','SC', 'Brasil')",
        "insert into tb_cidades values('BARRA VELHA','SC', 'Brasil')",
        "insert into tb_cidades values('BARRA GRANDE','SC', 'Brasil')",
        "insert into tb_cidades values('BARRA FRIA','SC', 'Brasil')",
        "insert into tb_cidades values('BARRA DA PRATA','SC', 'Brasil')",
        "insert into tb_cidades values('BARRA DA LAGOA','SC', 'Brasil')",
        "insert into tb_cidades values('BARRA CLARA','SC', 'Brasil')",
        "insert into tb_cidades values('BARRA BONITA','SC', 'Brasil')",
        "insert into tb_cidades values('BANDEIRANTE','SC', 'Brasil')",
        "insert into tb_cidades values('BALNEARIO MORRO DOS CONVENTOS','SC', 'Brasil')",
        "insert into tb_cidades values('BALNEARIO GAIVOTA','SC', 'Brasil')",
        "insert into tb_cidades values('BALNEARIO CAMBORIU','SC', 'Brasil')",
        "insert into tb_cidades values('BALNEARIO BARRA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('BALNEARIO ARROIO DO SILVA','SC', 'Brasil')",
        "insert into tb_cidades values('BAIA ALTA','SC', 'Brasil')",
        "insert into tb_cidades values('AZAMBUJA','SC', 'Brasil')",
        "insert into tb_cidades values('AURORA','SC', 'Brasil')",
        "insert into tb_cidades values('ATERRADO TORTO','SC', 'Brasil')",
        "insert into tb_cidades values('ATALANTA','SC', 'Brasil')",
        "insert into tb_cidades values('ASCURRA','SC', 'Brasil')",
        "insert into tb_cidades values('ARVOREDO','SC', 'Brasil')",
        "insert into tb_cidades values('ARROIO TRINTA','SC', 'Brasil')",
        "insert into tb_cidades values('ARNOPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('ARMAZEM','SC', 'Brasil')",
        "insert into tb_cidades values('ARARANGUA','SC', 'Brasil')",
        "insert into tb_cidades values('ARAQUARI','SC', 'Brasil')",
        "insert into tb_cidades values('ARABUTA','SC', 'Brasil')",
        "insert into tb_cidades values('APIUNA','SC', 'Brasil')",
        "insert into tb_cidades values('ANTONIO CARLOS','SC', 'Brasil')",
        "insert into tb_cidades values('ANTA GORDA','SC', 'Brasil')",
        "insert into tb_cidades values('ANITAPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('ANITA GARIBALDI','SC', 'Brasil')",
        "insert into tb_cidades values('ANGELINA','SC', 'Brasil')",
        "insert into tb_cidades values('ANCHIETA','SC', 'Brasil')",
        "insert into tb_cidades values('ALTO DA SERRA','SC', 'Brasil')",
        "insert into tb_cidades values('ALTO BELA VISTA','SC', 'Brasil')",
        "insert into tb_cidades values('ALTO ALEGRE','SC', 'Brasil')",
        "insert into tb_cidades values('ALFREDO WAGNER','SC', 'Brasil')",
        "insert into tb_cidades values('AIURE','SC', 'Brasil')",
        "insert into tb_cidades values('AGUTI','SC', 'Brasil')",
        "insert into tb_cidades values('AGUAS MORNAS','SC', 'Brasil')",
        "insert into tb_cidades values('AGUAS FRIAS','SC', 'Brasil')",
        "insert into tb_cidades values('AGUAS DE CHAPECO','SC', 'Brasil')",
        "insert into tb_cidades values('AGUAS CLARAS','SC', 'Brasil')",
        "insert into tb_cidades values('AGUAS BRANCAS','SC', 'Brasil')",
        "insert into tb_cidades values('AGUA DOCE','SC', 'Brasil')",
        "insert into tb_cidades values('AGRONOMICA','SC', 'Brasil')",
        "insert into tb_cidades values('AGROLANDIA','SC', 'Brasil')",
        "insert into tb_cidades values('ABELARDO LUZ','SC', 'Brasil')",
        "insert into tb_cidades values('ABDON BATISTA','SC', 'Brasil')",
        "insert into tb_cidades values('PRESIDENTE KENNEDY','SC', 'Brasil')",
        "insert into tb_cidades values('PRESIDENTE JUSCELINO','SC', 'Brasil')",
        "insert into tb_cidades values('PRESIDENTE GETULIO','SC', 'Brasil')",
        "insert into tb_cidades values('PRESIDENTE CASTELO BRANCO','SC', 'Brasil')",
        "insert into tb_cidades values('PRATA','SC', 'Brasil')",
        "insert into tb_cidades values('PRAIA GRANDE','SC', 'Brasil')",
        "insert into tb_cidades values('POUSO REDONDO','SC', 'Brasil')",
        "insert into tb_cidades values('PORTO UNIAO','SC', 'Brasil')",
        "insert into tb_cidades values('PORTO BELO','SC', 'Brasil')",
        "insert into tb_cidades values('PONTE SERRADA','SC', 'Brasil')",
        "insert into tb_cidades values('PONTE ALTA DO NORTE','SC', 'Brasil')",
        "insert into tb_cidades values('PONTE ALTA','SC', 'Brasil')",
        "insert into tb_cidades values('POMERODE','SC', 'Brasil')",
        "insert into tb_cidades values('POCO PRETO','SC', 'Brasil')",
        "insert into tb_cidades values('PLANALTO ALEGRE','SC', 'Brasil')",
        "insert into tb_cidades values('PLANALTO','SC', 'Brasil')",
        "insert into tb_cidades values('PIRATUBA','SC', 'Brasil')",
        "insert into tb_cidades values('PIRABEIRABA','SC', 'Brasil')",
        "insert into tb_cidades values('PINHEIROS','SC', 'Brasil')",
        "insert into tb_cidades values('PINHEIRO PRETO','SC', 'Brasil')",
        "insert into tb_cidades values('PINHEIRAL','SC', 'Brasil')",
        "insert into tb_cidades values('PINDOTIBA','SC', 'Brasil')",
        "insert into tb_cidades values('PINHALZINHO','SC', 'Brasil')",
        "insert into tb_cidades values('PICARRAS','SC', 'Brasil')",
        "insert into tb_cidades values('PETROLANDIA','SC', 'Brasil')",
        "insert into tb_cidades values('PESCARIA BRAVA','SC', 'Brasil')",
        "insert into tb_cidades values('PERITIBA','SC', 'Brasil')",
        "insert into tb_cidades values('PERICO','SC', 'Brasil')",
        "insert into tb_cidades values('PENHA','SC', 'Brasil')",
        "insert into tb_cidades values('PEDRAS GRANDES','SC', 'Brasil')",
        "insert into tb_cidades values('PAULO LOPES','SC', 'Brasil')",
        "insert into tb_cidades values('PAULA PEREIRA','SC', 'Brasil')",
        "insert into tb_cidades values('PASSOS MAIA','SC', 'Brasil')",
        "insert into tb_cidades values('PASSO MANSO','SC', 'Brasil')",
        "insert into tb_cidades values('PASSO DE TORRES','SC', 'Brasil')",
        "insert into tb_cidades values('PARAISO','SC', 'Brasil')",
        "insert into tb_cidades values('PAPANDUVA','SC', 'Brasil')",
        "insert into tb_cidades values('PANTANO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('PALMITOS','SC', 'Brasil')",
        "insert into tb_cidades values('PALMEIRA','SC', 'Brasil')",
        "insert into tb_cidades values('PALMA SOLA','SC', 'Brasil')",
        "insert into tb_cidades values('PALHOCA','SC', 'Brasil')",
        "insert into tb_cidades values('PAINEL','SC', 'Brasil')",
        "insert into tb_cidades values('PAIAL','SC', 'Brasil')",
        "insert into tb_cidades values('OURO VERDE','SC', 'Brasil')",
        "insert into tb_cidades values('OURO','SC', 'Brasil')",
        "insert into tb_cidades values('OTACILIO COSTA','SC', 'Brasil')",
        "insert into tb_cidades values('ORLEANS','SC', 'Brasil')",
        "insert into tb_cidades values('NOVO HORIZONTE','SC', 'Brasil')",
        "insert into tb_cidades values('NOVA VENEZA','SC', 'Brasil')",
        "insert into tb_cidades values('NOVA TRENTO','SC', 'Brasil')",
        "insert into tb_cidades values('NOVA TEUTONIA','SC', 'Brasil')",
        "insert into tb_cidades values('NOVA PETROPOLIS','SC', 'Brasil')",
        "insert into tb_cidades values('NOVA ITABERABA','SC', 'Brasil')",
        "insert into tb_cidades values('NOVA GUARITA','SC', 'Brasil')",
        "insert into tb_cidades values('NOVA ERECHIM','SC', 'Brasil')",
        "insert into tb_cidades values('NOVA CULTURA','SC', 'Brasil')",
        "insert into tb_cidades values('NOSSA SENHORA DE CARAVAGGIO','SC', 'Brasil')",
        "insert into tb_cidades values('NAVEGANTES','SC', 'Brasil')",
        "insert into tb_cidades values('MORRO GRANDE','SC', 'Brasil')",
        "insert into tb_cidades values('MORRO DO MEIO','SC', 'Brasil')",
        "insert into tb_cidades values('MORRO DA FUMACA','SC', 'Brasil')",
        "insert into tb_cidades values('MORRO CHATO','SC', 'Brasil')",
        "insert into tb_cidades values('MONTE CASTELO','SC', 'Brasil')",
        "insert into tb_cidades values('MONTE CARLO','SC', 'Brasil')",
        "insert into tb_cidades values('MONTE ALEGRE','SC', 'Brasil')",
        "insert into tb_cidades values('MONDAI','SC', 'Brasil')",
        "insert into tb_cidades values('MODELO','SC', 'Brasil')",
        "insert into tb_cidades values('MIRIM DOCE','SC', 'Brasil')",
        "insert into tb_cidades values('MIRIM','SC', 'Brasil')",
        "insert into tb_cidades values('MIRADOR','SC', 'Brasil')",
        "insert into tb_cidades values('MELEIRO','SC', 'Brasil')",
        "insert into tb_cidades values('MATOS COSTA','SC', 'Brasil')",
        "insert into tb_cidades values('MASSARANDUBA','SC', 'Brasil')",
        "insert into tb_cidades values('MAROMBAS BOSSARDI','SC', 'Brasil')",
        "insert into tb_cidades values('MAROMBAS','SC', 'Brasil')",
        "insert into tb_cidades values('MARIFLOR','SC', 'Brasil')",
        "insert into tb_cidades values('MAREMA','SC', 'Brasil')",
        "insert into tb_cidades values('MARECHAL BORMANN','SC', 'Brasil')",
        "insert into tb_cidades values('MARCILIO DIAS','SC', 'Brasil')",
        "insert into tb_cidades values('MARAVILHA','SC', 'Brasil')",
        "insert into tb_cidades values('MARATA','SC', 'Brasil')",
        "insert into tb_cidades values('MARARI','SC', 'Brasil')",
        "insert into tb_cidades values('MARACAJA','SC', 'Brasil')",
        "insert into tb_cidades values('MAJOR VIEIRA','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA HELENA','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA IZABEL','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA LUCIA','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA MARIA','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA ROSA DE LIMA','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA ROSA DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA TEREZINHA','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA TEREZINHA DO PROGRESSO','SC', 'Brasil')",
        "insert into tb_cidades values('SANTA TEREZINHA DO SALTO','SC', 'Brasil')",
        "insert into tb_cidades values('SANTIAGO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('SANTO AMARO DA IMPERATRIZ','SC', 'Brasil')",
        "insert into tb_cidades values('SANTO ANTONIO DE LISBOA','SC', 'Brasil')",
        "insert into tb_cidades values('SAO BENTO BAIXO','SC', 'Brasil')",
        "insert into tb_cidades values('SAO BENTO DO SUL','SC', 'Brasil')",
        "insert into tb_cidades values('SAO BERNARDINO','SC', 'Brasil')",
        };

        for (String cidade: cidades){
            db.execSQL(cidade);
        }

    }

}
